version: "1"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend-nodejs
    command: npm run dev
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://root:root@db:5431/note_db

  db:
    image: postgres:17.6
    environment:
      - POSTGRES_DB=note_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5431:5431"
